
services:
  # nest:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  redis:
    image: redis:6.2.3
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s
  mysql:
    # image: mysql:8.0.25
    image: mysql/mysql-server:8.0.25
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=wjdgyqja88
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./migration:/docker-entrypoint-initdb.d/
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=wjdgyqja88 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s

